-- 20260901000000_baseline_schema.sql
--
-- Reverse-engineered from the live `fashionmind` project (cxfsiotzfshrjdrctmge)
-- on 2026-09-06. The original tables were created ad hoc via the Supabase
-- dashboard / MCP and never captured in a migration, so `supabase db reset`
-- had nothing to build. This is that baseline.
--
-- Every statement is `if not exists` / `add column if not exists` guarded, so
-- applying it to the existing project is a no-op. Identity columns replace the
-- original `default nextval(seq)` so the schema is portable to a fresh stack.
--
-- Scope: the 15 FashionMind tables. The `fraudguard` project shares this
-- database (alerts, predictions, drift_snapshots, model_registry, alert_rules)
-- and is intentionally not reproduced here.

create table if not exists public.articles (
  article_id text primary key,
  product_code text, product_name text, product_type_name text,
  product_group_name text, graphical_appearance text, colour_group_name text,
  garment_group_name text, department_name text, section_name text,
  detail_desc text,
  avg_price numeric(10,2),
  popularity_score numeric(7,6) default 0,
  trend_score numeric(7,6) default 0,
  created_at timestamptz default now()
);

create table if not exists public.customers (
  customer_id text primary key,
  age smallint, age_bucket text,
  club_member_status text default 'NONE',
  fashion_news_freq text,
  active boolean default true,
  engagement_score numeric(5,4) default 0.5,
  age_norm numeric(5,4) default 0.3,
  avg_price numeric(10,2),
  top_product_type text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_auth (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  password_hash text not null,
  customer_id text,
  name text, phone text,
  created_at timestamptz default now(),
  last_login timestamptz
);
create unique index if not exists user_auth_email_key on public.user_auth (lower(email));

create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  article_id text not null,
  t_dat date not null,
  price numeric(10,4),
  sales_channel_id smallint,
  week date,
  created_at timestamptz default now()
);
create index if not exists interactions_customer_idx on public.interactions (customer_id);

create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  article_id text not null,
  score numeric(8,6),
  rank smallint,
  model_version text default 'v1',
  is_cold_start boolean default false,
  reason_1 text, reason_2 text, reason_3 text,
  occasion text,
  generated_at timestamptz default now(),
  clicked boolean, clicked_at timestamptz,
  purchased boolean, purchased_at timestamptz
);
create index if not exists recommendations_customer_idx on public.recommendations (customer_id);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  customer_id text,
  started_at timestamptz default now(),
  ended_at timestamptz,
  turn_count integer default 0,
  metadata jsonb default '{}'::jsonb
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null,
  content text,
  tool_name text, tool_input jsonb, tool_result jsonb,
  tokens_in integer, tokens_out integer, latency_ms integer,
  created_at timestamptz default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  article_id text not null,
  size text,
  quantity smallint default 1,
  price numeric(10,2),
  added_at timestamptz default now(),
  mode text not null default 'demo',
  source text, retailer text, buy_url text, title text, image text, look text,
  currency text default 'INR'
);
create unique index if not exists cart_items_customer_id_article_id_size_key
  on public.cart_items (customer_id, article_id, coalesce(size, ''));

create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  article_id text not null,
  added_at timestamptz default now()
);
create unique index if not exists wishlists_customer_article_key
  on public.wishlists (customer_id, article_id);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  status text default 'pending',
  total_amount numeric(10,2),
  address jsonb,
  payment_method text,
  placed_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  article_id text not null,
  size text,
  quantity smallint default 1,
  price numeric(10,2)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  article_id text not null,
  rating smallint,
  title text, body text,
  created_at timestamptz default now()
);

create table if not exists public.trend_scores (
  id bigint generated by default as identity primary key,
  week date not null,
  product_type_name text not null,
  trend_score numeric(7,6),
  unit_sales integer,
  revenue numeric(12,2),
  predicted_sales numeric(12,2),
  mape numeric(8,4),
  created_at timestamptz default now(),
  unique (week, product_type_name)
);

create table if not exists public.outfit_pairs (
  id bigint generated by default as identity primary key,
  anchor_id text not null,
  pair_id text not null,
  similarity numeric(7,6),
  pair_type text,
  created_at timestamptz default now()
);

create table if not exists public.ab_test_results (
  id bigint generated by default as identity primary key,
  model_a text not null,
  model_b text not null,
  ctr_a numeric(8,6), ctr_b numeric(8,6),
  lift_pct numeric(10,4),
  p_value numeric(8,6),
  significant boolean,
  ci_lo numeric(8,6), ci_hi numeric(8,6),
  n_users_a integer, n_users_b integer,
  note text,
  run_at timestamptz default now()
);

-- RLS is enabled + locked by the later migrations (002 / 005). Enable it here
-- too so a fresh stack is never briefly open.
do $$
declare t text;
begin
  foreach t in array array[
    'articles','customers','user_auth','interactions','recommendations',
    'chat_sessions','chat_messages','cart_items','wishlists','orders',
    'order_items','reviews','trend_scores','outfit_pairs','ab_test_results']
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;
